name: movieboxclone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  chewie: ^1.5.0
  dio: ^5.4.3+1
  file_picker: ^5.2.10
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  hive: ^2.2.3
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  mime: ^1.0.5
  motion_toast: ^2.10.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  share_plus: ^6.3.4
  shared_preferences: ^2.2.3
  staggered_grid_view_flutter: ^0.0.4
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3
  youtube_player_flutter: ^9.0.1
  youtube_video_player: ^0.1.1
  # package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  test: ^1.25.2

dependency_overrides:
  webview_flutter_android: 3.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/food_banana.jpg
    - assets/images/food_brussels_sprouts.jpg
    - assets/images/food_burger.jpg
    - assets/images/food_cucumber.jpg
    - assets/images/food_cupcake.jpg
    - assets/images/food_salmon.jpg
    - assets/images/ypf.png
    # 2Geda asset
    - assets/2geda/
    - assets/2geda/images/
    - assets/2geda/adverts/
    - assets/2geda/icons/
    - images/
