name: torihd
description: A new Flutter project.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  chewie: ^1.5.0
  cloud_firestore: ^5.1.0
  dio: ^5.4.3+1
  file_picker: ^5.2.10
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.7
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.2.0
  hive: ^2.2.3
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  mime: ^1.0.5
  motion_toast: ^2.10.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  share_plus: ^6.3.4
  shared_preferences: ^2.2.3
  staggered_grid_view_flutter: ^0.0.4
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3
  youtube_player_flutter: ^8.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  test: ^1.25.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo1.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo1.jpg"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/logo1.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo1.jpg"

dependency_overrides:
  webview_flutter_android: 3.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/food_banana.jpg
    - assets/images/food_brussels_sprouts.jpg
    - assets/images/food_burger.jpg
    - assets/images/food_cucumber.jpg
    - assets/images/food_cupcake.jpg
    - assets/images/food_salmon.jpg
    - assets/images/ypf.png
