// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfjVpdATsvbeiZB_2nDXdGDYtLlajRfM',
    appId: '1:113549816013:web:04e1b8088366379a3fb984',
    messagingSenderId: '113549816013',
    projectId: 'torihd-1ed20',
    authDomain: 'torihd-1ed20.firebaseapp.com',
    databaseURL: 'https://torihd-1ed20-default-rtdb.firebaseio.com',
    storageBucket: 'torihd-1ed20.appspot.com',
    measurementId: 'G-JJ1Q2TV79M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDITfxQG0x_CCjf_T7dOO9MEjC0fRPlQnI',
    appId: '1:113549816013:android:e0ab942772fdcd8d3fb984',
    messagingSenderId: '113549816013',
    projectId: 'torihd-1ed20',
    databaseURL: 'https://torihd-1ed20-default-rtdb.firebaseio.com',
    storageBucket: 'torihd-1ed20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlRX2J_xpzQ61GUhuxH9XQJPA8kWmwUQM',
    appId: '1:113549816013:ios:9f78565340f02a913fb984',
    messagingSenderId: '113549816013',
    projectId: 'torihd-1ed20',
    databaseURL: 'https://torihd-1ed20-default-rtdb.firebaseio.com',
    storageBucket: 'torihd-1ed20.appspot.com',
    iosClientId:
        '113549816013-kv1thh3ni6jcng5rprp72faogm01pedk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlRX2J_xpzQ61GUhuxH9XQJPA8kWmwUQM',
    appId: '1:113549816013:ios:9f78565340f02a913fb984',
    messagingSenderId: '113549816013',
    projectId: 'torihd-1ed20',
    databaseURL: 'https://torihd-1ed20-default-rtdb.firebaseio.com',
    storageBucket: 'torihd-1ed20.appspot.com',
    iosClientId:
        '113549816013-kv1thh3ni6jcng5rprp72faogm01pedk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tori',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRfjVpdATsvbeiZB_2nDXdGDYtLlajRfM',
    appId: '1:113549816013:web:72d2736a32728ba23fb984',
    messagingSenderId: '113549816013',
    projectId: 'torihd-1ed20',
    authDomain: 'torihd-1ed20.firebaseapp.com',
    databaseURL: 'https://torihd-1ed20-default-rtdb.firebaseio.com',
    storageBucket: 'torihd-1ed20.appspot.com',
    measurementId: 'G-9VTVN37QEL',
  );
}
